# Generated by Django 5.2.14 on 2026-05-27 14:27

import chat.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_sender_room_creator_room_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif", "webp", "mp3", "ogg", "wav"]
                    ),
                    chat.models.validate_file_size,
                ],
            ),
        ),
    ]
